###
GET https://vn-public-apis.fpo.vn/provinces/getAll?limit=-1

//Đăng ký
POST http://localhost:6868/api/auth/register
Content-Type: application/json

{
    "email": "usertest@gmail.com",
    "password": "123456",
    "username": "test"
}


//Đăng nhập
###
POST http://localhost:6868/api/auth/login
Content-Type: application/json

{
    "email": "admin12345@gmail.com",
    "password": "123456"
}
###
GET http://localhost:6868/api/auth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsImlzQWRtaW4iOjEsImlhdCI6MTY3OTkzMzMyMX0.WsMzyoVbwermRpqjizQFtbPgXwHhaQYE2QLyUtCcwPo


###
GET http://localhost:6868/api/user/alluser?id=30
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsImlzQWRtaW4iOjEsImlhdCI6MTY4MTQ4MDU1MX0.YW65k89HCWqEad5MtS5ym4FUQB0GBgT1FLWLFnLLgaQ
###
POST http://localhost:6868/api/auth/login
Content-Type: application/json

{
    "email": "admin12345@gmail.com",
    "password": "123456"
}

###
POST http://localhost:6868/api/auth/login
Content-Type: application/json

{
    "email": "daoquynanh@gmail.com",
    "password": "123456"
}





//Cập nhật thông tin người dùng
###
PUT http://localhost:6868/api/user/update/27
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjgsImlzQWRtaW4iOjAsImlhdCI6MTY3ODgxNDk3N30.6Uf8qp4v22rLF6bNIcQ0bv6rqpVbUq4jTmobZjuJedU

{
    "username": "Update người khác",
    "avatar": "123456",
    "birthday": 2004
}


//Xoá người dùng
###
PUT http://localhost:6868/api/user/delete/28
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjgsImlzQWRtaW4iOjAsImlhdCI6MTY3ODgxNTMxOX0.DigTVavsIZqRt2oFx6-7OHE7fQ0tm19V353hMXiYpb4

{
    "deleted": 1
}

//Get ALL user
###
GET http://localhost:6868/api/user/alluser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsImlzQWRtaW4iOjEsImlhdCI6MTY3ODg2NzA3OH0.DkwthZ_rA0DPgr-GhLB5xfGa9TgvrRVY2cxTkNTLJzc



//Xoá người dùng
###
POST http://localhost:6868/api/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsImlzQWRtaW4iOjEsImlhdCI6MTY4MzYyNDcyMX0.NxldlqNFhAcmcSH3QrDChuEZa4ClVkkN7TTO-BYsEFo

{
    "name": "New Product", 
    "description": "hihi ", 
    "information": "Máy mới 100%", 
    "status": "Còn hàng", 
    "img": "https://cdn2.cellphones.com.vn/358x358,webp,q100/media/catalog/product/v/_/v_ng_18.png", 
    "id_owner": 2, 
    "id_category": 1
}

//Xoá người dùng
###
PUT http://localhost:6868/api/product/update/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsImlzQWRtaW4iOjEsImlhdCI6MTY3ODgxNzAwNn0.Uv0hjCyuewE0_eWITKCeKq8AncT6-l0-Ny8Tn752G08

{
    "name": "iPhone XS", 
    "description": "iPhone 6s", 
    "information": "Máy mới 100% ", 
    "status": "Còn hàng", 
    "img": "https://cdn2.cellphones.com.vn/358x358,webp,q100/media/catalog/product/v/_/v_ng_18.png", 
    "id_owner": 1, 
    "id_category": 1
}


//Xoá người dùng
###
PUT http://localhost:6868/api/product/delete/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsImlzQWRtaW4iOjEsImlhdCI6MTY3ODgxNzAwNn0.Uv0hjCyuewE0_eWITKCeKq8AncT6-l0-Ny8Tn752G08

{
    "deleted": 1
}



###
GET http://localhost:3000/api/product
Content-Type: application/json

###
GET http://localhost:6868/api/product/page
Content-Type: application/json




//Thêm mới thông tin sản phẩm

###
POST http://localhost:6868/api/filter
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsImlzQWRtaW4iOjEsImlhdCI6MTY3ODg2NzA3OH0.DkwthZ_rA0DPgr-GhLB5xfGa9TgvrRVY2cxTkNTLJzc

{
    "id_pro": 2, 
    "size": "512GB", 
    "color": "Black",
    "quantity": 8,
    "price": 9999
}


###
PUT http://localhost:6868/api/filter/update/17
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsImlzQWRtaW4iOjEsImlhdCI6MTY3ODg2NzA3OH0.DkwthZ_rA0DPgr-GhLB5xfGa9TgvrRVY2cxTkNTLJzc

{
    "id_pro": 2, 
    "size": "64GB", 
    "color": "White",
    "quantity": 2,
    "price": 6868
}
###
GET http://localhost:6868/api/category
Content-Type: application/json

###
GET http://localhost:6868/api/producer
Content-Type: application/json



###
GET http://localhost:6868/api/filter/find/2
Content-Type: application/json

###
GET http://localhost:6868/api/filter/details?idpro=2&size=128GB&color=Black
Content-Type: application/json


###
GET http://localhost:6868/api/filter/searchsize?color=Black&idpro=2
Content-Type: application/json

###
GET http://localhost:6868/api/filter/img?color=Black&idpro=2
Content-Type: application/json

###
GET http://localhost:6868/api/filter/searchcolor?size=64GB&idpro=2
Content-Type: application/json

###
GET http://localhost:6868/api/filter/details?size=128GB&idpro=2&color=Gold
Content-Type: application/json


//Tạo giỏ hàng mới cho người dùng
###
GET http://localhost:6868/api/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzQsImlzQWRtaW4iOjAsImlhdCI6MTY4MTA1NTk5M30.bnD-lJ1J0Q0wOkP5Ng5vtzAy5M-C95hTZvg1OOTDUdk
###
POST http://localhost:6868/api/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsImlzQWRtaW4iOjEsImlhdCI6MTY4MTAzMzEyNH0.QDY2JCAAFHJTTj5_oEL2BI58xy1MvcKClEHyB6e8DYw

{
    "filter": 10,
    "quantity": 2,
    "subtotal": 2400
}


//GET CART
###
PUT http://localhost:6868/api/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsImlzQWRtaW4iOjEsImlhdCI6MTY4MTA2MjM5NX0.EtrxEqCj5YCB9F-6uzcCCgI3MVh_9jSbye17yxylJEA

{
    "quantity": 99,
    "id_filter": 10
}
###


///Cart details
###
GET http://localhost:6868/api/cartdetail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsImlzQWRtaW4iOjAsImlhdCI6MTY3OTkzNjExN30.x6mClHjIoZE_gykdo_sCEfZqDZoHQ1I__J4sjNPEOpw
###

###
PUT http://localhost:6868/api/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsImlzQWRtaW4iOjAsImlhdCI6MTY3OTkzNjExN30.x6mClHjIoZE_gykdo_sCEfZqDZoHQ1I__J4sjNPEOpw
###
///Cart details
###
POST http://localhost:6868/api/cartdetail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsImlzQWRtaW4iOjAsImlhdCI6MTY3OTkzNjExN30.x6mClHjIoZE_gykdo_sCEfZqDZoHQ1I__J4sjNPEOpw

{
    "id_cart" : 2, 
    "id_filter" : 8,
    "quantity" : 3, 
    "subtotal" : 3000
}
###



###
GET http://localhost:6868/api/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzQsImlzQWRtaW4iOjAsImlhdCI6MTY4MTIwNzg1NX0.Ez96r7tLmDB_cm3EH0-5W0caDLYkHEhmu4RabqX4BuM


###
GET http://localhost:6868/api/order/cancel
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsImlzQWRtaW4iOjEsImlhdCI6MTY4MTIxMjcyNX0.0p5m8-68PMw1hoSEcX2GsBQrt0GmCY8CAXo6R1svmG8


###
GET http://localhost:6868/api/order_detail/8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzQsImlzQWRtaW4iOjAsImlhdCI6MTY4MTIwNzg1NX0.Ez96r7tLmDB_cm3EH0-5W0caDLYkHEhmu4RabqX4BuM

###
PUT http://localhost:6868/api/order/30
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsImlzQWRtaW4iOjEsImlhdCI6MTY4MTIxMjcyNX0.0p5m8-68PMw1hoSEcX2GsBQrt0GmCY8CAXo6R1svmG8

{
    "id": 13
}


//Get đơn hàng by Admin
###
GET http://localhost:6868/api/order/byAdmin?success=true
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzQsImlzQWRtaW4iOjAsImlhdCI6MTY4MTMyMjE1M30.a-BOhCvVDdF-HE8JJb48sw4bt-A8Mq4jRCv_2BTNRWQ


//Get đơn hàng by Admin
###
PUT http://localhost:6868/api/order/byAdmin/13
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsImlzQWRtaW4iOjEsImlhdCI6MTY4MTM5NjYzMn0.J9qDaIKoS5t70A7Kh5gWQ4k1GnCuPiktG6EONTIhtEE



//GET ALL PRODUCT BY ADMIN
//Xoá người dùng
###
GET http://localhost:6868/api/product/byAdmin?page=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsImlzQWRtaW4iOjEsImlhdCI6MTY4MTM5NjYzMn0.J9qDaIKoS5t70A7Kh5gWQ4k1GnCuPiktG6EONTIhtEE

//thống kê
###

GET http://localhost:6868/api/stat/sold/31
Content-Type: application/json
###

GET http://localhost:6868/api/stat/bought/33
Content-Type: application/json
###
GET http://localhost:6868/api/stat/stat-byUser/33
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsImlzQWRtaW4iOjEsImlhdCI6MTY4NDMzMTk3Mn0.jBKpZfW9w5gl5BaiEMaY_PSmkS6zhI8Fk3HGs9nEqBM
###
GET http://localhost:6868/api/stat/count
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsImlzQWRtaW4iOjEsImlhdCI6MTY4NDMwNTMxNH0._mZUO9ghw-jtk3rD0bUFUPjwLx9xyzm2cpIfxIfwCiI
